# File mode creation mask - allows to create files with a write permission for the group
# The user inside of the docker container and a user on the host belong to the same group 'zpp'
umask 002

PS1='\[\033[01m\][ \[\033[01;34m\]\u \[\033[00m\]\[\033[01m\]] \[\033[01;32m\]\w\[\033[00m\] \[\033[01;34m\]$\[\033[00m\]> '

alias ls='ls --color=auto'
